services:
  app:
    container_name: seabattle_app
    build:
      context: .
    ports:
      - "8001:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - .env.docker

  db:
    container_name: seabattle_db
    image: postgres:latest
    ports:
      - "5435:5432"
    env_file:
      - .env.docker